name: Docs

on:
  workflow_run:
    workflows: ["Release"]
    types:
      - completed
jobs:
  on-sucess:
      if: ${{ github.event.workflow_run.conclusion == 'success' }}
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - run: rustup target add thumbv7m-none-eabi
        
        # - name: Install cargo-audit
        #   run: cargo install cargo-audit

        - name: Generate docs
          run: cargo doc

        # - name: Audit dependencies
        #   run: cargo audit