name: Docs

on:
  workflow_run:
    workflows: ["Release"]
    types:
      - completed

jobs:
  on-success:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: thumbv7m-none-eabi

      - name: Generate documentation
        run: cargo doc --target thumbv7m-none-eabi --no-deps

      # - name: Install cargo-audit
      #   run: cargo install cargo-audit

      # - name: Audit dependencies
      #   run: cargo audit