name: Docs

on:
  workflow_run:
    workflows: ["Release"]
jobs:
  on-sucess:
      runs-on: ubuntu-latest
      steps:
        - name: Cache Cargo
          run: |
            cargo doc
            cargo audit